name = "freedb"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "freedb"
database_id = "6de3a526-b3b2-47ab-a6df-59cb5c907929"

# 本地开发配置
[vars]
ENVIRONMENT = "development"

# 生产环境配置
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "freedb"
database_id = "6de3a526-b3b2-47ab-a6df-59cb5c907929"
[env.production.vars]
ENVIRONMENT = "production"
